"""Added youtube link to user table

Revision ID: 0a400ed66a85
Revises: 461772a24b35
Create Date: 2020-09-18 13:04:54.793872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a400ed66a85'
down_revision = '461772a24b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
