"""added adress and donation

Revision ID: 0eb82e58834d
Revises: a8ed694c5225
Create Date: 2020-10-15 14:45:49.736617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb82e58834d'
down_revision = 'a8ed694c5225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation', sa.Boolean(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('zipcode')
        batch_op.drop_column('street')
        batch_op.drop_column('number')
        batch_op.drop_column('location')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('donation')

    # ### end Alembic commands ###
