"""change order product relation

Revision ID: 334c280eada5
Revises: c7e107ba876b
Create Date: 2020-09-09 16:52:02.465026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334c280eada5'
down_revision = 'c7e107ba876b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.String(length=128), nullable=False))
        batch_op.drop_constraint('orders_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_product_id_fkey', 'products', ['product_id'], ['id'])
        batch_op.drop_column('order')

    # ### end Alembic commands ###
