"""added images columns to posts and updates

Revision ID: 3a19c4088070
Revises: 2d428aa6af06
Create Date: 2020-09-04 15:26:17.597384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a19c4088070'
down_revision = '2d428aa6af06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.String(length=128), nullable=True))

    with op.batch_alter_table('updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('updates', schema=None) as batch_op:
        batch_op.drop_column('images')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
