"""Added images to product

Revision ID: 461772a24b35
Revises: 1dc6039d97f0
Create Date: 2020-09-12 17:21:35.364485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461772a24b35'
down_revision = '1dc6039d97f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
