"""added images to newsletter

Revision ID: a66a569727e7
Revises: abd8be186a16
Create Date: 2020-11-11 17:11:22.291683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66a569727e7'
down_revision = 'abd8be186a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
