"""Added youtube link to user table

Revision ID: a8ed694c5225
Revises: 0a400ed66a85
Create Date: 2020-09-18 15:14:53.347820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ed694c5225'
down_revision = '0a400ed66a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_length', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('youtube_length')

    # ### end Alembic commands ###
