"""Added descr shop to users

Revision ID: dc5bd854a50d
Revises: e2a3654a2db9
Create Date: 2020-10-25 18:21:25.752595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5bd854a50d'
down_revision = 'e2a3654a2db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopdescription', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('shopdescription')

    # ### end Alembic commands ###
