"""Added image2 and image3 to products

Revision ID: f1b348045e33
Revises: 1f07f6827a3a
Create Date: 2020-10-29 16:52:39.355091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b348045e33'
down_revision = '1f07f6827a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    # ### end Alembic commands ###
