"""added sendpayment column to order

Revision ID: f2bd89e5fd44
Revises: 88aa2e9ec1ce
Create Date: 2020-09-09 14:33:09.345163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bd89e5fd44'
down_revision = '88aa2e9ec1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sendpayment', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('sendpayment')

    # ### end Alembic commands ###
